import type { Metadata } from "next";
import Link from "next/link";
import MobileScrollableNav from "./components/MobileScrollableNav";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LogoIndia from "../../logoUpdated.png";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ backgroundColor: "white", color: "black" }}
      >
        <div className="min-h-screen flex flex-col" style={{ backgroundColor: "white", color: "black" }}>
          <header
            className="top-0 z-50 backdrop-blur border-b"
            style={{
              backgroundColor: "white",
              borderColor: "black",
            }}
          >
            <Link
              style={{
                display: "flex",
                justifyContent: "center",
                alignItems: "center",
                padding: "8px",
              }}
              href="/"
              passHref
            >
              <img
                src={LogoIndia.src}
                alt="SND Regenic Research Labs Pvt. Ltd., India Logo"
                style={{
                  width: "30%",
                  height: "auto",
                  borderRadius: "16px",
                  cursor: "pointer",
                  backgroundColor: "white",
                }}
              />
            </Link>

            <nav className="hidden md:flex max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 h-16 items-center justify-around">
              <ul className="flex items-center gap-6 text-m">
                <li>
                  <Link className="hover:no-underline" href="/about">
                    About Us
                  </Link>
                </li>
                <li>
                  <Link className="hover:no-underline" href="/products-services">
                    Product & Services
                  </Link>
                </li>
                <li>
                  <Link className="hover:no-underline" href="/research-developments">
                    Research & Developments
                  </Link>
                </li>
                <li>
                  <Link className="hover:no-underline" href="/news-events">
                    News & Events
                  </Link>
                </li>
                <li>
                  <Link className="hover:no-underline" href="/contact-us">
                    Contact Us
                  </Link>
                </li>
              </ul>
            </nav>

            {/* Mobile horizontal scroller */}
            <MobileScrollableNav />
          </header>

          <main className="flex-1" style={{ backgroundColor: "white", color: "black" }}>
            {children}
          </main>

          <footer
            className="py-8 text-sm"
            style={{
              backgroundColor: "white",
              color: "black",
              borderTop: "1px solid black",
            }}
          >
            <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col sm:flex-row items-center justify-center gap-4">
              <p>© {new Date().getFullYear()} SND REGENIC Research Labs Pvt. Ltd., India</p>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
